const mouseEvent = {    // : MouseEvent
  altKey: false,
  button: 0,
  buttons: 0,
  clientX: 42,
  clientY: 84,
  ctrlKey: false,
  fromElement: null,
  layerX: 42,
  layerY: 84,
  metaKey: false,
  movementX:  0,
  movementY: 0,
  offsetX: 42,
  offsetY: 84,
  pageX: 42,
  pageY: 84,
  relatedTarget: null,
  screenX: 142,
  screenY: 184,
  shiftKey: false,
  toElement: null,
  which: 1,
  x: 42,
  y: 84,
  getModifierState: () => false,
  initMouseEvent: () => {},
  detail: 1,
  view: window,
  initUIEvent: () => {},
  bubbles: true,
  cancelBubble: false,
  cancelable: true,
  currentTarget: null,
  defaultPrevented: false,
  eventPhase: 0,
  isTrusted: true,
  returnValue: true,
  scoped: false,
  srcElement: null,
  target: null,
  timeStamp: 4284,
  type: 'click',
  deepPath: () => null,
  initEvent: () => {},
  preventDefault: () => {},
  stopImmediatePropagation: () => {},
  stopPropagation: () => {},
  AT_TARGET: null,
  BUBBLING_PHASE: 0,
  CAPTURING_PHASE: 0,
  NONE: 0,
};

export default mouseEvent;
